package com.example.bipl.biplpos.dao.ws;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 28/03/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.*;

import java.util.Hashtable;

public class PUVwsResponse extends AttributeContainer implements KvmSerializable
{

    
    public String panNo;
    
    public String statusCode;
    
    public String statusDescription;
    
    public String ibUser;
    
    public String responseCode;
    
    public String responseDescription;
    
    public String expiryDate;
    
    public String STAN;

    public PUVwsResponse ()
    {
    }

    public PUVwsResponse (Object paramObj,PUVExtendedSoapSerializationEnvelope __envelope)
    {

	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("panNo"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.panNo = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.panNo = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("statusCode"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.statusCode = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.statusCode = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("statusDescription"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.statusDescription = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.statusDescription = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("ibUser"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.ibUser = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.ibUser = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("responseCode"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.responseCode = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.responseCode = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("responseDescription"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.responseDescription = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.responseDescription = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("expiryDate"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.expiryDate = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.expiryDate = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("STAN"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.STAN = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.STAN = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.panNo!=null?this.panNo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.statusCode!=null?this.statusCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.statusDescription!=null?this.statusDescription:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.ibUser!=null?this.ibUser:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.responseCode!=null?this.responseCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.responseDescription!=null?this.responseDescription:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.expiryDate!=null?this.expiryDate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.STAN!=null?this.STAN:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "panNo";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "statusCode";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "statusDescription";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ibUser";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "responseCode";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "responseDescription";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "expiryDate";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "STAN";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

