package com.example.bipl.biplpos.dao.ws;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 28/03/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.*;

import java.util.Hashtable;

public class PUVwsParam extends AttributeContainer implements KvmSerializable
{

    
    public String username;
    
    public String password;
    
    public String panNo;
    
    public String requestCode;
    
    public String STAN;

    public PUVwsParam ()
    {
    }

    public PUVwsParam (Object paramObj,PUVExtendedSoapSerializationEnvelope __envelope)
    {

	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("username"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.username = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.username = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("password"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.password = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.password = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("panNo"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.panNo = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.panNo = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("requestCode"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.requestCode = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.requestCode = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("STAN"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.STAN = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.STAN = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.username!=null?this.username:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.password!=null?this.password:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.panNo!=null?this.panNo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.requestCode!=null?this.requestCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.STAN!=null?this.STAN:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "username";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "password";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "panNo";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "requestCode";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "STAN";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

